pipeline {
  agent { docker { image 'python' } }

    stages {
        stage('Build') {
            steps {
                'sh 'python --version''
            }
        }
        stage('Test') {
            steps {
                
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
