pipeline {
  agent { docker { image 'python' } }

    stages {
        stage('Build') {
            steps {
                'sh 'python --version''
            }
        }
        stage('script execution') {
            steps {
               'sh 'python ./day2training/script.py''
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
