pipeline {
  agent { docker { image 'python' } }

    stages {
      
        stage ('Checkout') {
			       steps {
				           git 'https://github.com/rpreeth/training.git'
		             	}
        }
        stage('Build') {
            steps {
                'sh 'python --version''
            }
        }
        stage('script execution') {
            steps {
               'sh 'python ./day2learning/script.py''
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
